### ISSUE TITLE
Unable to build with debug information

### ISSUE THREAD

**Issue by W4RH4WK** [allscale/allscale_runtime#18]
I am unable to build the current version of the runtime with debug symbols. I just added `-DCMAKE_BUILD_TYPE=Debug` to the CMake call.

HPX: 35428360f0cbde7f9ff697008649dbc75c0a67e2
API: c81015dc5339a9af834c5d760fe3ca18636bbf5c

The full log file can be found [here](https://gist.github.com/W4RH4WK/92028c2d53941c696df327474ed574c7).

**Comment by sithhell** [comment]
HPX needs to be built in debug as well. There are no guarantees about
mixing build types.

**Comment by W4RH4WK** [comment]
Thanks, that piece of information solved it.
