### ISSUE TITLE
AllScale Executable can not support flags.

### ISSUE THREAD

**Issue by HerbertJordan** [allscale/allscale_runtime#24]
When attempting to add a -C flag to ipic3d we realized that we receive an error regarding an unsupported flag. The -h flag is also hijacked by HPX to print the HPX flag help, not the ipic3d help.

There should be an alternative way of passing runtime "flags" to the runtime system than to redirect user flags. Maybe pass them through some environment variable? Alternatively, HPX flag interception should be restricted only to --hpx flags.

**Comment by sithhell** [comment]
This has been fixed.
